# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning/io/events.proto

require 'google/protobuf'

require 'lightning/wire/types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "lightning.io.events.PeerConnected" do
    optional :remote_node_id, :string, 1
  end
  add_message "lightning.io.events.PeerAlreadyConnected" do
    optional :remote_node_id, :string, 1
  end
  add_message "lightning.io.events.PeerDisconnected" do
    optional :remote_node_id, :string, 1
  end
end

module Lightning
  module Io
    module Events
      PeerConnected = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightning.io.events.PeerConnected").msgclass
      PeerAlreadyConnected = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightning.io.events.PeerAlreadyConnected").msgclass
      PeerDisconnected = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightning.io.events.PeerDisconnected").msgclass
    end
  end
end
