# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning/router/events.proto

require 'google/protobuf'

require 'lightning/wire/types_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "lightning.router.events.ChannelRegistered" do
    optional :short_channel_id, :uint64, 1
  end
  add_message "lightning.router.events.ChannelUpdated" do
    optional :short_channel_id, :uint64, 1
  end
end

module Lightning
  module Router
    module Events
      ChannelRegistered = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightning.router.events.ChannelRegistered").msgclass
      ChannelUpdated = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightning.router.events.ChannelUpdated").msgclass
    end
  end
end
