# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning/router/messages.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "lightning.router.messages.RouteDiscovered" do
    repeated :routing_info, :message, 1, "lightning.router.messages.RoutingInfo"
  end
  add_message "lightning.router.messages.RoutingInfo" do
    optional :pubkey, :string, 1
    optional :short_channel_id, :uint64, 2
    optional :fee_base_msat, :uint64, 3
    optional :fee_proportional_millionths, :uint64, 4
    optional :cltv_expiry_delta, :uint32, 5
  end
  add_message "lightning.router.messages.RouteNotFound" do
    optional :source_node_id, :string, 1
    optional :target_node_id, :string, 2
  end
end

module Lightning
  module Router
    module Messages
      RouteDiscovered = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightning.router.messages.RouteDiscovered").msgclass
      RoutingInfo = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightning.router.messages.RoutingInfo").msgclass
      RouteNotFound = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightning.router.messages.RouteNotFound").msgclass
    end
  end
end
