# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning/wire/types.proto

require 'google/protobuf'

Google::Protobuf::DescriptorPool.generated_pool.build do
end

module Lightning
  module Wire
  end
end
