# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: lightning/grpc/service.proto for package 'lightning.grpc'

require 'grpc'
require 'lightning/grpc/service_pb'

module Lightning
  module Grpc
    module LightningService
      class Service

        include GRPC::GenericService

        self.marshal_class_method = :encode
        self.unmarshal_class_method = :decode
        self.service_name = 'lightning.grpc.LightningService'

        rpc :Events, stream(EventsRequest), stream(EventsResponse)
        rpc :Connect, ConnectRequest, stream(ConnectResponse)
        rpc :Open, OpenRequest, stream(OpenResponse)
        rpc :Invoice, InvoiceRequest, InvoiceResponse
        rpc :Payment, PaymentRequest, stream(PaymentResponse)
        rpc :Route, RouteRequest, stream(RouteResponse)
      end

      Stub = Service.rpc_stub_class
    end
  end
end
