# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: lightning/grpc/service.proto

require 'google/protobuf'

require 'lightning/channel/events_pb'
require 'lightning/payment/events_pb'
Google::Protobuf::DescriptorPool.generated_pool.build do
  add_message "lightning.grpc.EventsRequest" do
    optional :operation, :enum, 1, "lightning.grpc.Operation"
    optional :event_type, :string, 2
  end
  add_message "lightning.grpc.EventsResponse" do
    oneof :event do
      optional :channel_created, :message, 201, "lightning.channel.events.ChannelCreated"
      optional :channel_restored, :message, 202, "lightning.channel.events.ChannelRestored"
      optional :channel_id_assigned, :message, 203, "lightning.channel.events.ChannelIdAssigned"
      optional :short_channel_id_assigned, :message, 204, "lightning.channel.events.ShortChannelIdAssigned"
      optional :local_channel_update, :message, 205, "lightning.channel.events.LocalChannelUpdate"
      optional :local_channel_down, :message, 206, "lightning.channel.events.LocalChannelDown"
      optional :channel_state_changed, :message, 208, "lightning.channel.events.ChannelStateChanged"
      optional :channel_signature_received, :message, 209, "lightning.channel.events.ChannelSignatureReceived"
      optional :channel_closed, :message, 210, "lightning.channel.events.ChannelClosed"
      optional :payment_sent, :message, 301, "lightning.payment.events.PaymentSent"
      optional :payment_relayed, :message, 302, "lightning.payment.events.PaymentRelayed"
      optional :payment_received, :message, 303, "lightning.payment.events.PaymentReceived"
      optional :payment_succeeded, :message, 304, "lightning.payment.events.PaymentSucceeded"
    end
  end
  add_enum "lightning.grpc.Operation" do
    value :SUBSCRIBE, 0
    value :UNSUBSCRIBE, 1
  end
end

module Lightning
  module Grpc
    EventsRequest = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightning.grpc.EventsRequest").msgclass
    EventsResponse = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightning.grpc.EventsResponse").msgclass
    Operation = Google::Protobuf::DescriptorPool.generated_pool.lookup("lightning.grpc.Operation").enummodule
  end
end
